-- +goose Up
ALTER TABLE IF EXISTS incidents
  ADD COLUMN IF NOT EXISTS school_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS county_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS county_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sub_county_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sub_county_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_serial TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_asset_tag TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_model_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_make TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_model TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_category TEXT NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS work_orders
  ADD COLUMN IF NOT EXISTS school_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_serial TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_asset_tag TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_model_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_make TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_model TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS device_category TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE IF EXISTS incidents
  DROP COLUMN IF EXISTS school_name,
  DROP COLUMN IF EXISTS county_id,
  DROP COLUMN IF EXISTS county_name,
  DROP COLUMN IF EXISTS sub_county_id,
  DROP COLUMN IF EXISTS sub_county_name,
  DROP COLUMN IF EXISTS contact_name,
  DROP COLUMN IF EXISTS contact_phone,
  DROP COLUMN IF EXISTS contact_email,
  DROP COLUMN IF EXISTS device_serial,
  DROP COLUMN IF EXISTS device_asset_tag,
  DROP COLUMN IF EXISTS device_model_id,
  DROP COLUMN IF EXISTS device_make,
  DROP COLUMN IF EXISTS device_model,
  DROP COLUMN IF EXISTS device_category;

ALTER TABLE IF EXISTS work_orders
  DROP COLUMN IF EXISTS school_name,
  DROP COLUMN IF EXISTS contact_name,
  DROP COLUMN IF EXISTS contact_phone,
  DROP COLUMN IF EXISTS contact_email,
  DROP COLUMN IF EXISTS device_serial,
  DROP COLUMN IF EXISTS device_asset_tag,
  DROP COLUMN IF EXISTS device_model_id,
  DROP COLUMN IF EXISTS device_make,
  DROP COLUMN IF EXISTS device_model,
  DROP COLUMN IF EXISTS device_category;
